# Generated by Django 3.1 on 2020-08-27 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airliner', models.CharField(max_length=32)),
                ('flight_no', models.CharField(default='#', max_length=32)),
                ('trip_type', models.CharField(default='#', max_length=32)),
                ('airport', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=320)),
                ('depart_date', models.DateTimeField(default=django.utils.timezone.now, max_length=32)),
                ('destination', models.CharField(max_length=32)),
                ('seat_capacity', models.IntegerField(default=200)),
            ],
        ),
    ]
